[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "weebit"
version = "1.0.0"
description = "A deterministic, high-performance link shortener application."
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "Sam Milburn" }
]
dependencies = [
    "fastapi>=0.110.0",
    "uvicorn[standard]>=0.28.0",
    "pydantic>=2.6.0",
    "sqlalchemy[asyncio]>=2.0.0",
    "asyncpg>=0.29.0",
    "alembic>=1.13.0",
    "pydantic-settings>=2.15.0",
    "dotenv>=0.9.9",
    "aiocache>=0.12.3",
]

# Configure hatchling to find source code in src/weebit
[tool.hatch.build.targets.wheel]
packages = ["src/weebit"]
