"""Create links table

Revision ID: 6423d4dbc3fa
Revises: 
Create Date: 2026-09-20 13:39:06.120385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6423d4dbc3fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('short_ref_code', sa.String(length=10), nullable=False),
    sa.Column('normalised_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_ref_code')
    )
    op.create_index('ix_links_short_ref_code_hash', 'links', ['short_ref_code'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_links_short_ref_code_hash', table_name='links', postgresql_using='hash')
    op.drop_table('links')
    # ### end Alembic commands ###
